fc2/collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "fc2/base_footprint"
    odom_frame_id: "fc2/odom"
    cmd_vel_in_topic: "/fc2/cmd_vel_smoothed"
    cmd_vel_out_topic: "/fc2/cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    polygons: [ "PolygonStop", "PolygonSlow" ]
    PolygonStop:
      type: "polygon"
      points: [0.3, 0.3, 0.3, -0.3, -0.2, -0.3, -0.2, 0.3]
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "/fc2/polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.5, 0.5, 0.5, -0.5, -0.3, -0.5, -0.3, 0.5]
      action_type: "slowdown"
      min_points: 4
      slowdown_ratio: 0.2
      visualize: True
      polygon_pub_topic: "/fc2/polygon_slowdown"

    # observation sources parameters
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/fc2/scan"
